"""Setup script for Nexus-LLM."""

from setuptools import setup, find_packages

setup(
    name="nexus-llm",
    version="0.1.0",
    description="A powerful LLM framework for training, serving, and chatting",
    long_description=open("README.md", encoding="utf-8").read() if __import__("os").path.exists("README.md") else "",
    long_description_content_type="text/markdown",
    author="Nexus-LLM Team",
    author_email="nexus-llm@example.com",
    url="https://github.com/nexus-llm/nexus-llm",
    license="MIT",
    packages=find_packages(exclude=["tests", "tests.*", "docs", "examples"]),
    python_requires=">=3.9",
    install_requires=[
        "torch>=2.0.0",
        "transformers>=4.35.0",
        "accelerate>=0.24.0",
        "peft>=0.6.0",
        "datasets>=2.14.0",
        "tokenizers>=0.14.0",
        "fastapi>=0.104.0",
        "uvicorn[standard]>=0.24.0",
        "websockets>=12.0",
        "click>=8.1.0",
        "rich>=13.0.0",
        "prompt-toolkit>=3.0.0",
        "pyyaml>=6.0",
        "requests>=2.31.0",
        "tqdm>=4.66.0",
        "numpy>=1.24.0",
        "pandas>=2.0.0",
        "scikit-learn>=1.3.0",
        "matplotlib>=3.7.0",
        "safetensors>=0.4.0",
        "scipy>=1.11.0",
    ],
    extras_require={
        "gpu": [
            "xformers>=0.0.22",
            "flash-attn>=2.3.0",
        ],
        "dev": [
            "pytest>=7.4.0",
            "pytest-cov>=4.1.0",
            "pytest-asyncio>=0.21.0",
            "black>=23.0.0",
            "flake8>=6.1.0",
            "mypy>=1.5.0",
            "isort>=5.12.0",
            "pre-commit>=3.5.0",
        ],
        "quantization": [
            "bitsandbytes>=0.41.0",
            "auto-gptq>=0.6.0",
            "optimum>=1.14.0",
        ],
        "all": [
            "nexus-llm[gpu,dev,quantization]",
        ],
    },
    entry_points={
        "console_scripts": [
            "nexus-llm=main:main",
            "nexus=main:main",
        ],
    },
    classifiers=[
        "Development Status :: 3 - Alpha",
        "Intended Audience :: Developers",
        "Intended Audience :: Science/Research",
        "License :: OSI Approved :: MIT License",
        "Programming Language :: Python :: 3",
        "Programming Language :: Python :: 3.9",
        "Programming Language :: Python :: 3.10",
        "Programming Language :: Python :: 3.11",
        "Programming Language :: Python :: 3.12",
        "Topic :: Scientific/Engineering :: Artificial Intelligence",
        "Topic :: Software Development :: Libraries :: Python Modules",
    ],
    keywords=["llm", "nlp", "machine-learning", "deep-learning", "transformers", "chat", "training"],
    project_urls={
        "Bug Tracker": "https://github.com/nexus-llm/nexus-llm/issues",
        "Documentation": "https://nexus-llm.readthedocs.io",
        "Source Code": "https://github.com/nexus-llm/nexus-llm",
    },
)
